# Generated by Django 2.2.28 on 2023-03-15 04:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import recipes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('name', models.CharField(help_text='Дайте название категории подборок', max_length=200, verbose_name='Название')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название', max_length=200, verbose_name='Ингредиент')),
                ('description', models.TextField(help_text='Опишите ингредиент', verbose_name='Описание')),
                ('species', models.CharField(blank=True, help_text='Укажите подвид, если нужно', max_length=200, verbose_name='Подвид')),
                ('image', models.ImageField(help_text='Загрузите картинку ингредиента', upload_to='ingredients/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('title', models.CharField(help_text='Дайте название рецепту', max_length=200, verbose_name='Название')),
                ('description', models.TextField(help_text='Опишите блюдо', verbose_name='Описание')),
                ('servings', models.PositiveSmallIntegerField(default=1, help_text='Укажите кол-во порций', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кол-во порций')),
                ('cooking_time', models.PositiveSmallIntegerField(help_text='Укажите время, необходимое для приготовления блюда', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(600)], verbose_name='Время приготовления')),
                ('ending_phrase', models.TextField(default='Приятного аппетита!', help_text='Завершите рецепт пожеланием приятного аппетита или вашей авторской фразой', verbose_name='Завершающая фраза')),
                ('video', models.FileField(help_text='Загрузите видео приготовления блюда по этому рецепту', upload_to='recipes/', verbose_name='Видео приготовления')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('title', models.CharField(help_text='Дайте название подборке', max_length=200, verbose_name='Название')),
                ('description', models.TextField(help_text='Опишите подборку', verbose_name='Описание')),
                ('cover', models.ImageField(help_text='Загрузите обложку для подборки', upload_to='selections/', verbose_name='Картинка')),
                ('category', models.ForeignKey(on_delete=models.SET(recipes.models.getDefaultCategory), related_name='selections', to='recipes.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Добавьте тег', max_length=50, unique=True, verbose_name='Тег')),
            ],
        ),
        migrations.CreateModel(
            name='SelectionRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Selection')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Укажите количество', verbose_name='Количество')),
                ('measurement_unit', models.CharField(choices=[('гр', 'гр'), ('кг', 'кг'), ('л', 'литр'), ('мл', 'мл'), ('ун', 'унция'), ('шт', 'шт'), ('щ', 'щепотка'), ('ч', 'чашка'), ('ч л', 'чайная ложка'), ('с л', 'столовая ложка'), ('д л', 'десертная ложка'), ('п', 'пинта'), ('пв', 'по вкусу')], help_text='Выберите единицу измерения', max_length=3, verbose_name='Единица измерения')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Загрузите картинку готового блюда', upload_to='recipes/', verbose_name='Фото')),
                ('is_cover', models.BooleanField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recipes.Recipe')),
            ],
        ),
    ]
